language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: make test
